/**
 * Skill Miner Types
 * Automatic skill discovery and generation from conversation patterns
 */

// Configuration
export interface SkillMinerConfig {
  enabled: boolean;
  minOccurrences: number;        // Minimum occurrences to consider (default: 3)
  similarityThreshold: number;   // Similarity threshold (default: 0.8)
  observationWindow: number;     // Observation window in days (default: 7)
  autoGenerate: boolean;         // Auto-generate skills without confirmation
  autoEvolve: boolean;           // Auto-evolve existing skills
  integration: {
    useMemory: boolean;          // Skills use memory
    saveOutcomes: boolean;       // Save execution outcomes to memory
    learnFromFailures: boolean;  // Learn from failures
  };
}

// Discovered potential skill
export interface PotentialSkill {
  id: string;
  name: string;
  description: string;
  triggerPatterns: string[];     // Trigger phrases
  workflowSteps: string[];       // Workflow steps
  toolsUsed: string[];           // Tools used
  entitiesInvolved: string[];    // Entities involved
  occurrenceCount: number;
  confidence: number;            // 0-1
  sourceSessions: string[];
  firstSeen: number;
  lastSeen: number;
  status: "pending" | "approved" | "rejected" | "generated";
}

// Skill generation result
export interface GeneratedSkill {
  metadata: {
    name: string;
    description: string;
    emoji: string;
    autoGenerated: true;
    sourceSessions: string[];
    generationDate: string;
    version: string;
  };
  content: string;               // Full SKILL.md content
  filePath: string;              // Target file path
}

// Skill execution log
export interface SkillExecution {
  skillName: string;
  sessionId: string;
  timestamp: number;
  input: string;
  output: string;
  success: boolean;
  duration: number;              // Execution duration in ms
  toolsUsed: string[];
  error?: string;
}

// Skill evaluation result
export interface SkillEvaluation {
  skillName: string;
  totalExecutions: number;
  successRate: number;
  avgDuration: number;
  lastUsed: number;
  trend: "improving" | "declining" | "stable";
  commonFailures: Array<{
    pattern: string;
    count: number;
  }>;
  suggestions: string[];
}

// Skill improvement suggestion
export interface ImprovementSuggestion {
  type: "add_step" | "remove_step" | "modify_step" | "add_example" | "add_tip" | "update_trigger";
  description: string;
  rationale: string;
  confidence: number;
  proposedChange: string;
}

// Skill evolution result
export interface SkillEvolution {
  skillName: string;
  originalVersion: string;
  newVersion: string;
  changes: Array<{
    type: string;
    description: string;
  }>;
  improvementScore: number;      // Estimated improvement
}

// Session analysis result
export interface SessionAnalysis {
  sessionId: string;
  timestamp: number;
  userIntent: string;
  workflow: string[];
  toolsUsed: string[];
  outcome: "success" | "failure" | "partial";
  entities: string[];
}

// Pattern match result
export interface PatternMatch {
  pattern: string;
  similarity: number;
  sessionIds: string[];
}

// Skill-memory bridge
export interface SkillMemoryContext {
  skillName: string;
  relevantMemories: Array<{
    type: "fact" | "preference" | "goal" | "past_execution";
    content: string;
    relevance: number;
  }>;
  entityContext: Record<string, string>;
}
